version: "3"

services:
  web:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POS_USERNAME}
      - POSTGRES_PASSWORD=${POS_PASSWORD}
      - POSTGRES_DB=${POS_DATABASE}
      - DATABASE_HOST=${POS_HOST}
    ports:
      - "${POS_PORT}:${POS_PORT}"
  redis:
    image: ${REDIS_IMAGE}
    ports:
     - "${REDIS_PORT}:${REDIS_PORT}"